spring:
  application:
    name: product
  profiles:
    active: dev
  jpa:
      show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.37.128/sell?characterEncoding=utf-8&useSSL=false